production:
  database: plextube_production
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password:
  pool: 5

development:
  database: plextube_development
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password:
  pool: 5

test:
  database: plextube_test
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password:
  pool: 5
