production:
  database: nottube_production
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password:
  pool: 5

development:
  database: nottube_development
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password:
  pool: 5

test:
  database: nottube_test
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password:
  pool: 5
