source 'https://rubygems.org'

ruby '2.6.3'

gem 'rails', '~> 6.0.2', '>= 6.0.2.1'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 4.1'
gem 'bootsnap'
gem 'google-api-client'
gem 'yt'
gem 'rack-cors'
gem 'mediainfo'
gem 'delayed_job_active_record'
gem "daemons"

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'pry'
  gem 'annotate', git: 'https://github.com/ctran/annotate_models.git'
end
