source 'https://rubygems.org'

ruby '~> 2.6.3'

gem 'rails', '~> 6.0.2', '>= 6.0.2.1'
gem 'sqlite3'
gem 'puma'
gem 'bootsnap'
gem 'google-api-client'
gem 'yt'
gem 'rack-cors'
gem 'mediainfo'
gem 'delayed_job_active_record'
gem "daemons"
gem 'clockwork'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'webmock'
  gem 'mocha'
end

group :development do
  gem 'listen'
  gem 'pry'
  gem 'annotate', git: 'https://github.com/ctran/annotate_models.git'
end
