source 'https://rubygems.org'

ruby '~> 2.6.3'

gem 'rails', '~> 6.0.2', '>= 6.0.2.1'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma'
gem 'bootsnap'
gem 'google-api-client'
gem 'rack-cors'
gem 'delayed_job_active_record'
gem 'clockwork'
gem 'zype'
gem 'rest-client'
gem 'redis'
gem 'redis-rails'

group :development do
  gem 'listen'
  gem 'annotate', git: 'https://github.com/ctran/annotate_models.git', require: false
end

group :development, :test do
  gem 'pry'
  gem 'webmock'
  gem 'mocha'
  gem 'fabrication'
end
